CREATE TABLE IF NOT EXISTS users (
	id	INTEGER PRIMARY KEY AUTOINCREMENT,
	userroles_id	INTEGER NOT NULL,
	Voornaam	INTEGER,
	Tussenvoegsel	INTEGER,
	Achternaam	INTEGER NOT NULL,
	Email	INTEGER NOT NULL,
	Wachtwoord	INTEGER NOT NULL,
	Telefoonnummer	INTEGER NOT NULL,
	Straat	INTEGER NOT NULL,
	Postcode	INTEGER NOT NULL,
	Huisnummer	INTEGER NOT NULL,
	BSN	INTEGER NOT NULL,
	Creditcard	INTEGER NOT NULL,
	Rijbewijs	BOOLEAN NOT NULL,
	
);